services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./config/docker.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - disknet

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: >
      migrate
      -path /migrations
      -database postgres://postgres:dev_only@postgres:5432/minecraft_server_creator_db?sslmode=disable
      up
    networks:
      - disknet
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" 
    env_file:
      - "./config/docker.env"
    volumes:
      - minio_data:/data
    networks:
      - disknet

  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    env_file:
      - ./config/docker.env
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - disknet

  user-service:
    build: ./services/user-service
    container_name: user-service
    env_file:
      - ./config/docker.env
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
      - "${USER_SERVICE_GRPC_SERVER_PORT}:${USER_SERVICE_GRPC_SERVER_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - disknet

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    env_file:
      - ./config/docker.env
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - disknet

  server-service:
    build: ./services/server-service
    container_name: server-service
    env_file:
      - ./config/docker.env
    volumes:
      - ./services/server-service/servers:/app/servers
    ports:
      - "${SERVER_SERVICE_PORT}:${SERVER_SERVICE_PORT}"
      - "25565:25565"
    depends_on:
      migrate:
        condition: service_completed_successfully
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - disknet

volumes:
  postgres_data:
  minio_data:

networks:
  disknet:
    driver: bridge
