services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./config/docker.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - disknet

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: >
      migrate
      -path /migrations
      -database postgres://postgres:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      up
    networks:
      - disknet

  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    env_file:
      - ./config/docker.env
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${API_GATEWAY_PORT}/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet

  user-service:
    build: ./services/user-service
    container_name: user-service
    env_file:
      - ./config/docker.env
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
      - "${USER_SERVICE_GRPC_SERVER_PORT}:${USER_SERVICE_GRPC_SERVER_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${USER_SERVICE_PORT}/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    env_file:
      - ./config/docker.env
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${AUTH_SERVICE_PORT}/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet

  server-service-v2:
    build: ./services/server-service-v2
    container_name: server-service-v2
    env_file:
      - ./config/docker.env
    ports:
      - "${SERVER_SERVICE_PORT}:${SERVER_SERVICE_PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${SERVER_SERVICE_PORT}/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet

volumes:
  postgres_data:

networks:
  disknet:
    driver: bridge
