services:
  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    env_file:
      - ./config/docker.env
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${API_GATEWAY_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - disknet
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./config/docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database",
        "postgres://postgres:dev_only@postgres:5432/minecraft_server_creator_db?sslmode=disable",
        "up"
      ]
    depends_on:
      - postgres
networks:
  disknet:
    driver: bridge

volumes:
  postgres_data: