services:
  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    env_file:
      - ./config/docker.env
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    depends_on:
      auth-service:
        condition: service_healthy
      file-storage:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${API_GATEWAY_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - disknet

networks:
  disknet:
    driver: bridge